In [1]:
import pandas as pd
import re

In [2]:
#input dataset unclean, and noisy

df_path = "D:\\vanshmalanidata\\Documents\\GitHub\\Uni-Dash_Reborn\\data"
df = pd.read_csv(df_path + "\\23DCS023_all_emails.csv")

In [3]:

USER_EMAIL = "23dcs023@charusat.edu.in"

# ---------------------------------------------------
# 1. REMOVE CHARUSAT DISCLAIMER
# ---------------------------------------------------
def remove_charusat_disclaimer(text):
    # Remove only the long legal footer, not message body
    pattern = r"(?is)disclaimer[:].*"
    return re.sub(pattern, "", str(text)).strip()


# ---------------------------------------------------
# 2. CLEAN TEXT
# ---------------------------------------------------
def clean_text(text):
    text = str(text)

    text = remove_charusat_disclaimer(text)

    # Remove generic signatures (keep forwarded content intact)
    text = re.sub(
        r"(?is)(thanks[,.]?$|regards[,.]?$|warm regards[,.]?$|best wishes[,.]?$)",
        "",
        text
    )

    # Remove long signature blocks if they are at the end (200 chars max)
    text = re.sub(r"(?is)(thanks|regards)[\s\S]{0,200}$", "", text)

    # Replace URLS using tokens for privacy
    text = re.sub(r"http\S+|www\.\S+", " <URL> ", text)


    # Collapse extra whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text.lower()


# ---------------------------------------------------
# 3. EMAIL + DOMAIN EXTRACTION
# ---------------------------------------------------
def extract_email(text):
    match = re.search(r'[\w\.-]+@[\w\.-]+', str(text))
    return match.group(0).lower() if match else ""

def extract_domain(email):
    return email.split('@')[-1] if "@" in email else ""




# ---------------------------------------------------
# 6. PIPELINE
# ---------------------------------------------------
cols_to_drop = ["Unnamed: 0", "id", "threadId", "labelIds", "snippet"]
df = df.drop(columns=[c for c in cols_to_drop if c in df.columns], errors="ignore")

df["raw_text"] = df["subject"].astype(str) + " " + df["content"].astype(str)
df["clean_text"] = df["raw_text"].apply(clean_text)

df["sender_email"] = df["from"].apply(extract_email)
df["sender_domain"] = df["sender_email"].apply(extract_domain)
    
df["label_source"] = ""
df["label_topic"] = ""
df["label_urgency"] = ""


# ---------------------------------------------------
# 7. FILTERING RULES
# ---------------------------------------------------

# Delete autosent classroom mails ( there is no point in keeping them)
df = df[df["sender_email"].str.lower() != "no-reply@classroom.google.com"]


# Keep short tiny urgent mails
df = df[df["clean_text"].str.len() > 5].reset_index(drop=True)

#remove self mails

df = df[df["sender_email"].str.lower() != USER_EMAIL]

df.head()

,from,subject,date,content,raw_text,clean_text,sender_email,sender_domain,label_source,label_topic,label_urgency
2,NPTEL <onlinecourses@nptel.iitm.ac.in>,NPTEL Newsletter: IIT Madras CODE Certificate ...,2025-06-25 15:52:01+05:30,<https://code.iitm.ac.in/foundations-to-ml>\r\...,NPTEL Newsletter: IIT Madras CODE Certificate ...,nptel newsletter: iit madras code certificate ...,onlinecourses@nptel.iitm.ac.in,nptel.iitm.ac.in,,,
3,Team at Read <support@e.read.ai>,Exclusive Education Pricing Just for You!,2025-06-25 09:33:48+00:00,"Read AI for $5 Per Month\r\nHi 23DCS023 , as a...",Exclusive Education Pricing Just for You! Read...,exclusive education pricing just for you! read...,support@e.read.ai,e.read.ai,,,
4,Mohini Darji <mohinidarji.dcs@charusat.ac.in>,Reg. Submission of SGP- Weekly reports,2025-06-25 13:36:47+05:30,"Dear Students,\r\n\r\nKindly find the attached...",Reg. Submission of SGP- Weekly reports Dear St...,reg. submission of sgp- weekly reports dear st...,mohinidarji.dcs@charusat.ac.in,charusat.ac.in,,,
5,Pinterest <recommendations@discover.pinterest....,Interaction Design for 23DCS023,2025-06-25 07:23:14+00:00,\r\nTo view this content open the following UR...,Interaction Design for 23DCS023 \r\nTo view th...,interaction design for 23dcs023 to view this c...,recommendations@discover.pinterest.com,discover.pinterest.com,,,
6,Sanket Suthar <sanketsuthar.it@charusat.ac.in>,"AWS Academy Batch Starting – 5th July, 10:30 A...",2025-06-25 10:09:42+05:30,"Dear All,\r\n\r\nThis is to inform you that th...","AWS Academy Batch Starting – 5th July, 10:30 A...","aws academy batch starting – 5th july, 10:30 a...",sanketsuthar.it@charusat.ac.in,charusat.ac.in,,,

In [4]:
print(f"the columns in the dataset are {df.columns} and there are a total of {len(df)} mails")

the columns in the dataset are Index(['from', 'subject', 'date', 'content', 'raw_text', 'clean_text',
       'sender_email', 'sender_domain', 'label_source', 'label_topic',
       'label_urgency'],
      dtype='object') and there are a total of 1522 mails

<h1>we want to reduce the features</h1>

In [5]:
unlabel_df = df[[
    "sender_email",
    "sender_domain",
    "subject",
    
    
    "clean_text",
    "label_source",
    "label_topic",
    "label_urgency"
]]

In [6]:
unlabel_df.to_csv("unlabeled_dataset.csv",index=False)

#locked the dataset down for level1 labelling, level2 labelling and llm inference later

<h1>now we move on to level 1 ie label source<h1>

In [7]:
from html import unescape
import os
from datetime import datetime

<h2>lets define the paths and input output</h2>

In [8]:

INPUT_FILE = "unlabeled_dataset.csv"
# OUTPUT_FILE = "source_labeled_dataset.csv"

# Output will be saved in a timestamped folder
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
OUTPUT_DIR = f"output_{timestamp}"
os.makedirs(OUTPUT_DIR, exist_ok=True)
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "source_labeled_dataset.csv")

INPUT_FILE = "unlabeled_dataset.csv"
# OUTPUT_FILE = "source_labeled_dataset.csv"

# Output will be saved in a timestamped folder
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
OUTPUT_DIR = f"output_{timestamp}"
os.makedirs(OUTPUT_DIR, exist_ok=True)
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "source_labeled_dataset.csv")

# ----------------------------------------------------------
# Level-1: Source Trust Classification (Identity-only)
# ----------------------------------------------------------

In [9]:

EXTERNAL_ACADEMIC_DOMAINS = {
    "nptel.iitm.ac.in",
    "nptel.ac.in",
    "coursera.org",
    "edx.org",
}

In [10]:

def classify_level1(sender_domain: str) -> str:
    """
    Level-1 classification determines the institutional trust level
    of the sender. It does NOT infer intent or topic.
    """

    sender_domain = (sender_domain or "").lower().strip()

    if not sender_domain:
        return "External / Misc"

    if sender_domain in EXTERNAL_ACADEMIC_DOMAINS:
        return "External Academic Platform"

    if sender_domain.endswith("charusat.ac.in"):
        return "Institutional Sender"

    if sender_domain.endswith("charusat.edu.in"):
        return "Student / Peer"

    return "External / Misc"

In [11]:
level1_df=pd.read_csv(INPUT_FILE, dtype=str, keep_default_na=False)

In [12]:
level1_df

,sender_email,sender_domain,subject,clean_text,label_source,label_topic,label_urgency
0,onlinecourses@nptel.iitm.ac.in,nptel.iitm.ac.in,NPTEL Newsletter: IIT Madras CODE Certificate ...,nptel newsletter: iit madras code certificate ...,,,
1,support@e.read.ai,e.read.ai,Exclusive Education Pricing Just for You!,exclusive education pricing just for you! read...,,,
2,mohinidarji.dcs@charusat.ac.in,charusat.ac.in,Reg. Submission of SGP- Weekly reports,reg. submission of sgp- weekly reports dear st...,,,
3,recommendations@discover.pinterest.com,discover.pinterest.com,Interaction Design for 23DCS023,interaction design for 23dcs023 to view this c...,,,
4,sanketsuthar.it@charusat.ac.in,charusat.ac.in,"AWS Academy Batch Starting – 5th July, 10:30 A...","aws academy batch starting – 5th july, 10:30 a...",,,
...,...,...,...,...,...,...,...
1517,iitbhubaneswartrainingcell@gmail.com,gmail.com,Exclusive Upskilling Program for CHARUSAT Firs...,exclusive upskilling program for charusat firs...,,,
1518,krishnapatel.ce@charusat.ac.in,charusat.ac.in,CE143- CCP Unit tese-1 Syllabus,"ce143- ccp unit tese-1 syllabus dear students,...",,,
1519,vaishalivadhavana.dcs@charusat.ac.in,charusat.ac.in,Regarding Permanent Student ID for FY 2023 CSE...,regarding permanent student id for fy 2023 cse...,,,
1520,mail-noreply@google.com,google.com,Tips for using your new inbox,tips for using your new inbox tips for using y...,,,
1521,mail-noreply@google.com,google.com,Get the official Gmail app,get the official gmail app get the official gm...,,,

<h2>applying source labels</h2>

In [13]:
level1_df["label_source"] = level1_df.apply(
        lambda r: classify_level1(
            r.get("sender_domain", ""),
        ),
        axis=1
    )

In [14]:
level1_df.to_csv(OUTPUT_FILE, index=False)

In [15]:
level1_df=pd.read_csv(OUTPUT_FILE)

In [16]:
level1_df

,sender_email,sender_domain,subject,clean_text,label_source,label_topic,label_urgency
0,onlinecourses@nptel.iitm.ac.in,nptel.iitm.ac.in,NPTEL Newsletter: IIT Madras CODE Certificate ...,nptel newsletter: iit madras code certificate ...,External Academic Platform,NaN,NaN
1,support@e.read.ai,e.read.ai,Exclusive Education Pricing Just for You!,exclusive education pricing just for you! read...,External / Misc,NaN,NaN
2,mohinidarji.dcs@charusat.ac.in,charusat.ac.in,Reg. Submission of SGP- Weekly reports,reg. submission of sgp- weekly reports dear st...,Institutional Sender,NaN,NaN
3,recommendations@discover.pinterest.com,discover.pinterest.com,Interaction Design for 23DCS023,interaction design for 23dcs023 to view this c...,External / Misc,NaN,NaN
4,sanketsuthar.it@charusat.ac.in,charusat.ac.in,"AWS Academy Batch Starting – 5th July, 10:30 A...","aws academy batch starting – 5th july, 10:30 a...",Institutional Sender,NaN,NaN
...,...,...,...,...,...,...,...
1517,iitbhubaneswartrainingcell@gmail.com,gmail.com,Exclusive Upskilling Program for CHARUSAT Firs...,exclusive upskilling program for charusat firs...,External / Misc,NaN,NaN
1518,krishnapatel.ce@charusat.ac.in,charusat.ac.in,CE143- CCP Unit tese-1 Syllabus,"ce143- ccp unit tese-1 syllabus dear students,...",Institutional Sender,NaN,NaN
1519,vaishalivadhavana.dcs@charusat.ac.in,charusat.ac.in,Regarding Permanent Student ID for FY 2023 CSE...,regarding permanent student id for fy 2023 cse...,Institutional Sender,NaN,NaN
1520,mail-noreply@google.com,google.com,Tips for using your new inbox,tips for using your new inbox tips for using y...,External / Misc,NaN,NaN
1521,mail-noreply@google.com,google.com,Get the official Gmail app,get the official gmail app get the official gm...,External / Misc,NaN,NaN

In [17]:
level1_df["label_source"].value_counts()

label_source
Institutional Sender          918
External / Misc               430
External Academic Platform    140
Student / Peer                 34
Name: count, dtype: int64

<h1> now we will shrink the dataset for llm inference</h1>

In [18]:
shrink_size = {
    "Institutional Sender": 70,
    "External / Misc": 40,
    "External Academic Platform": 25,
    "Student / Peer": 15,
}

In [19]:

samples = []

for source, n in shrink_size.items():
    subset = level1_df[level1_df["label_source"] == source]
    samples.append(subset.sample(n=n, random_state=42))

eval_df = pd.concat(samples).sample(frac=1, random_state=42).reset_index(drop=True)

eval_df.to_csv("llm_eval_subset_v1.csv", index=False)

In [22]:
print(eval_df["label_source"].value_counts())

label_source
Institutional Sender          70
External / Misc               40
External Academic Platform    25
Student / Peer                15
Name: count, dtype: int64

<h1>now it is time for llm inference</h1>

In [23]:
import os
import json
import requests
from datetime import datetime

In [24]:

INPUT_FILE = "llm_eval_subset_v1.csv"   # output of Level-1


OLLAMA_MODELS = [
    "qwen2.5:7b-instruct-q4_k_m",
    "mistral:7b-instruct-q4_k_m",
    #"phi3:medium-4k-instruct-q4_k_m",
]

OLLAMA_URL = "http://127.0.0.1:11434/api/generate"

LEVEL2_LABELS = [
    "Timetable / Schedule Update",
    "Exam Notifications",
    "Assignment or Submission",
    "Certification / Courses",
    "Internship / Placement Opportunities",
    "Events / Hackathons",
    "Important Announcements",
    "Administrative / Fees / Counselling",
    "General Information / Misc",
]

URGENCY_LABELS = ["Critical", "High", "Medium", "Low", "None"]

In [25]:

SYSTEM_PROMPT = f"""
You are an academic email assistant for a university student.

You will receive:
- SOURCE TRUST LEVEL (who sent the email)
- EMAIL SUBJECT
- EMAIL BODY

Important rules:
- Emails may be forwarded by faculty on behalf of administrative offices.
- Do NOT infer authority based only on sender.
- Decide topic and urgency from language, enforcement cues, deadlines, and tone.
- Output must be strictly valid JSON.
- Do NOT add explanations outside JSON.

Allowed topic labels:
{LEVEL2_LABELS}

Urgency definitions:
- Critical: deadline today or tomorrow; penalties if missed
- High: deadline within a few days; important action required
- Medium: relevant academic info, no immediate deadline
- Low: optional events or learning opportunities
- None: newsletters, promotions, routine info

Return JSON in this exact format:
{{
  "summary": "<one-line student-facing summary>",
  "label_topic": "<one of the allowed topic labels>",
  "label_urgency": "<one of the urgency labels>"
}}
"""

In [26]:
# ----------------------------------------------------------
# LLM Call
# ----------------------------------------------------------

def classify_email(label_source, subject, clean_text, model_name):
    prompt = f"""
SOURCE TRUST LEVEL: {label_source}
SUBJECT: {subject}

EMAIL CONTENT:
{clean_text}
"""

    response = requests.post(
        OLLAMA_URL,
        json={
            "model": model_name,
            "prompt": SYSTEM_PROMPT + "\n" + prompt,
            "stream": False,
            "options": {
                "temperature": 0,
                "top_p": 0.1
            }
        },
        timeout=60
    )

    response.raise_for_status()
    raw_output = response.json().get("response", "").strip()

    # ---- PRINT RAW LLM OUTPUT ----
    print("\n===== LLM RAW OUTPUT =====")
    print(raw_output)
    print("==========================\n")

    try:
        parsed = json.loads(raw_output)

        # ---- PRINT PARSED OUTPUT ----
        print(">>> PARSED RESULT:")
        print(parsed)
        print()

        return parsed

    except json.JSONDecodeError:
        print("!!! JSON PARSE FAILED — FALLING BACK !!!\n")
        return {
            "summary": "",
            "label_topic": "General Information / Misc",
            "label_urgency": "None"
        }

<h1>llm inference</h1>

In [27]:
emails_df = pd.read_csv(INPUT_FILE, dtype=str, keep_default_na=False)

In [28]:
emails_df

,sender_email,sender_domain,subject,clean_text,label_source,label_topic,label_urgency
0,recommendations@discover.pinterest.com,discover.pinterest.com,Form Design for 23DCS023,form design for 23dcs023 to view this content ...,External / Misc,,
1,nainaparmar.dcs@charusat.ac.in,charusat.ac.in,Fwd: Start Up Accelerator Program(SAP) initiat...,fwd: start up accelerator program(sap) initiat...,Institutional Sender,,
2,onlinecourses@nptel.iitm.ac.in,nptel.iitm.ac.in,Programming in Java - Week 09 Feedback Form,programming in java - week 09 feedback form nan,External Academic Platform,,
3,netacademail@external.cisco.com,external.cisco.com,NetAcad Student Newsletter – April 2025,netacad student newsletter – april 2025 hello ...,External / Misc,,
4,no-reply@accounts.google.com,accounts.google.com,Security alert,security alert [image: google] a new sign-in o...,External / Misc,,
...,...,...,...,...,...,...,...
145,pinterest-recommendations@ideas.pinterest.com,ideas.pinterest.com,"23DCS023, your taste is spot-on!","23dcs023, your taste is spot-on! to view this ...",External / Misc,,
146,team@kodekloud.com,kodekloud.com,"Spot the DevOps Skills Gap and fix it, step-by...","spot the devops skills gap and fix it, step-by...",External / Misc,,
147,kirtimakwana.mba@charusat.ac.in,charusat.ac.in,Re: DEPSTAR__ B.Tech CSE_ Sem -1_December 2023...,re: depstar__ b.tech cse_ sem -1_december 2023...,Institutional Sender,,
148,tanisha.singh@teachnook.com,teachnook.com,Training and Industrial internship for student...,training and industrial internship for student...,External / Misc,,
149,no-reply@leetcode.com,leetcode.com,LeetCode Weekly Digest,leetcode weekly digest nan,External / Misc,,

In [29]:
# Pick up to 10 emails, stratified by label_source
sampled_rows = []

for source in emails_df["label_source"].unique():
    subset = emails_df[emails_df["label_source"] == source]
    if not subset.empty:
        sampled_rows.append(subset.sample(n=1, random_state=42))

sampled_df = pd.concat(sampled_rows).head(10).reset_index(drop=True)

print(sampled_df["label_source"].value_counts())

label_source
External / Misc               1
Institutional Sender          1
External Academic Platform    1
Student / Peer                1
Name: count, dtype: int64

In [30]:
for model_name in OLLAMA_MODELS:
    print("\n" + "=" * 100)
    print(f"STARTING INFERENCE WITH MODEL: {model_name}")
    print("=" * 100 + "\n")

    for idx, row in sampled_df.iterrows():
        print("\n" + "-" * 80)
        print(f"EMAIL {idx + 1}")
        print(f"SOURCE: {row['label_source']}")
        print(f"SUBJECT: {row.get('subject', '')}")
        print(f"BODY:\n{row['clean_text']}")
        print("-" * 80)

        result = classify_email(
            label_source=row["label_source"],
            subject=row.get("subject", ""),
            clean_text=row.get("clean_text", ""),
            model_name=model_name
        )

        print("FINAL OUTPUT:")
        print(result)

    cont_model = input(
        f"\nFinished all emails for model '{model_name}'. "
        "Continue to next model? (y/n): "
    ).strip().lower()

    if cont_model != "y":
        break

====================================================================================================
STARTING INFERENCE WITH MODEL: qwen2.5:7b-instruct-q4_k_m
====================================================================================================


--------------------------------------------------------------------------------
EMAIL 1
SOURCE: External / Misc
SUBJECT: INVITATION FOR INTERNSHIP AND JOB ASSISTANCE WITH IIT-BHUBANESWAR
BODY:
invitation for internship and job assistance with iit-bhubaneswar *dear students of charusat university,* *greetings from teachnook!* teachnook in collaboration with *wissenaire iit bhubaneswar ,ibm ,microsoft *is organizing a 2 months of training + internship program. we are enrolling only *limited students *in the program for *charusat* *university* *interested students fill out the below google form, * <url> *find the below attachments for reference:* *first month: *iit training has been designed in the form of live lectures along with living mentorship from industry professionals. (login credentials will be provided to students after registration) *second month: *internship with live mentorship for projects from professionals. the live industry project will be giving students experience in solving real-world problems. *project 1:-* 10 individual projects assigned to each intern which they have to complete with their mentor . *project 2:-* capstone project: it's a group project assigned to a group of 15 interns. for each intern particular work will be assigned to them they have to work on it. (essential data and materials required for the project will be provided by the company side itself) here are two types of classes we are providing: *1. blended program/recorded classes:* you will receive recorded sessions, whatever doubts you have you can clear it in live doubt clearing sessions which will be organized every weekend. *2. mentor led/live classes: *you will be having live zoom classes at 6:30pm for 2 to 3 days a week. you will get your recorded sessions as well lms(learning management system) portal where you will have access to it for 6 months. *after completion of the program the student shall receive a:* ✅ program completion certificate issued by iit bhubaneswar (wissenaire). ✅ co-branded internship certificate from top mncs. ✅ 100% placement assistance. ✅ access to a growing community. *linkedin profile:- <url> < <url> -- -- mahima , team leader 6363428432
--------------------------------------------------------------------------------

===== LLM RAW OUTPUT =====
{
  "summary": "Invitation for internship and job assistance program with IIT-Bhubaneswar",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Invitation for internship and job assistance program with IIT-Bhubaneswar', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'Medium'}

FINAL OUTPUT:
{'summary': 'Invitation for internship and job assistance program with IIT-Bhubaneswar', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'Medium'}

--------------------------------------------------------------------------------
EMAIL 2
SOURCE: Institutional Sender
SUBJECT: CHARUSAT - FMS - IIIM - Invitation @ Prabandhan 2023 (Exhibition cum Sale) - Inaugural Ceremony
BODY:
charusat - fms - iiim - invitation @ prabandhan 2023 (exhibition cum sale) - inaugural ceremony dear all, greetings! we are thrilled to inform you all that indukaka ipcowala institute of management (iiim) is organizing *prabandhan – 2023 *during november 03-06, 2023 (10:00 am to 09:00 pm). prabandhan is a student-driven event wherein the students collaborate closely with the industries, entrepreneurs, gruh udhyog, and smes to understand the product, devise marketing strategies, learn financial management, negotiation skills, and ultimately sell the product. all students are invited to visit the exhibition and motivate the student participants. *please find the attached invitation and product poster herewith this mail.* *hoping to see you all at prabandhan 2023.* *
--------------------------------------------------------------------------------

===== LLM RAW OUTPUT =====
{
  "summary": "Invitation to attend Prabandhan 2023 Exhibition cum Sale Inaugural Ceremony",
  "label_topic": "Events / Hackathons",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'Invitation to attend Prabandhan 2023 Exhibition cum Sale Inaugural Ceremony', 'label_topic': 'Events / Hackathons', 'label_urgency': 'Low'}

FINAL OUTPUT:
{'summary': 'Invitation to attend Prabandhan 2023 Exhibition cum Sale Inaugural Ceremony', 'label_topic': 'Events / Hackathons', 'label_urgency': 'Low'}

--------------------------------------------------------------------------------
EMAIL 3
SOURCE: External Academic Platform
SUBJECT: Feedback/Queries regarding March 23, 2025 - NPTEL Exams
BODY:
feedback/queries regarding march 23, 2025 - nptel exams nan
--------------------------------------------------------------------------------

===== LLM RAW OUTPUT =====
{
  "summary": "Review or ask questions about the March 23, 2025 NPTEL exam details.",
  "label_topic": "Exam Notifications",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Review or ask questions about the March 23, 2025 NPTEL exam details.', 'label_topic': 'Exam Notifications', 'label_urgency': 'Medium'}

FINAL OUTPUT:
{'summary': 'Review or ask questions about the March 23, 2025 NPTEL exam details.', 'label_topic': 'Exam Notifications', 'label_urgency': 'Medium'}

--------------------------------------------------------------------------------
EMAIL 4
SOURCE: Student / Peer
SUBJECT: Gujarat Cultural Elocution Competition – 2025 (University Level) || Registration Deadline: March 6, 2025, 8:00 PM
BODY:
gujarat cultural elocution competition – 2025 (university level) || registration deadline: march 6, 2025, 8:00 pm dear cspit & depstar students, the charusat nss unit is organizing the *university level gujarat cultural elocution competition – 2025* as part of the initiative by the state nss department. we invite interested students to participate and showcase their oratory skills. *date:* march 8, 2025 *time:* 12:15 pm (updated) onwards *venue: *rpcp auditorium *levels:* university → zone → state *topics (choose one):* - character building for nation building - importance of constitution in a citizen’s life - youth: the future of the nation – challenges and responsibilities - values, morality, and ethics: pillars of indian culture - developed india 2047: vision for a better future *eligibility:* participants must be born on or after january 1, 1999. *registration deadline:* march 6, 2025, 8:00 pm *registration link:* <goog_111173522> <url> for further details, please refer to the attached pdfs. for any queries, contact: - *mr. kishan patel* (nss coordinator) – +91 97244 42255 - *mr. dhruv rupapara* (student coordinator) – +91 63539 33976 *we encourage students to participate.* best regards, *nss unit, charusat* ---
--------------------------------------------------------------------------------

===== LLM RAW OUTPUT =====
{
  "summary": "Last chance to register for Gujarat Cultural Elocution Competition by March 6, 2025, 8:00 PM",
  "label_topic": "Events / Hackathons",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Last chance to register for Gujarat Cultural Elocution Competition by March 6, 2025, 8:00 PM', 'label_topic': 'Events / Hackathons', 'label_urgency': 'High'}

FINAL OUTPUT:
{'summary': 'Last chance to register for Gujarat Cultural Elocution Competition by March 6, 2025, 8:00 PM', 'label_topic': 'Events / Hackathons', 'label_urgency': 'High'}

====================================================================================================
STARTING INFERENCE WITH MODEL: mistral:7b-instruct-q4_k_m
====================================================================================================


--------------------------------------------------------------------------------
EMAIL 1
SOURCE: External / Misc
SUBJECT: INVITATION FOR INTERNSHIP AND JOB ASSISTANCE WITH IIT-BHUBANESWAR
BODY:
invitation for internship and job assistance with iit-bhubaneswar *dear students of charusat university,* *greetings from teachnook!* teachnook in collaboration with *wissenaire iit bhubaneswar ,ibm ,microsoft *is organizing a 2 months of training + internship program. we are enrolling only *limited students *in the program for *charusat* *university* *interested students fill out the below google form, * <url> *find the below attachments for reference:* *first month: *iit training has been designed in the form of live lectures along with living mentorship from industry professionals. (login credentials will be provided to students after registration) *second month: *internship with live mentorship for projects from professionals. the live industry project will be giving students experience in solving real-world problems. *project 1:-* 10 individual projects assigned to each intern which they have to complete with their mentor . *project 2:-* capstone project: it's a group project assigned to a group of 15 interns. for each intern particular work will be assigned to them they have to work on it. (essential data and materials required for the project will be provided by the company side itself) here are two types of classes we are providing: *1. blended program/recorded classes:* you will receive recorded sessions, whatever doubts you have you can clear it in live doubt clearing sessions which will be organized every weekend. *2. mentor led/live classes: *you will be having live zoom classes at 6:30pm for 2 to 3 days a week. you will get your recorded sessions as well lms(learning management system) portal where you will have access to it for 6 months. *after completion of the program the student shall receive a:* ✅ program completion certificate issued by iit bhubaneswar (wissenaire). ✅ co-branded internship certificate from top mncs. ✅ 100% placement assistance. ✅ access to a growing community. *linkedin profile:- <url> < <url> -- -- mahima , team leader 6363428432
--------------------------------------------------------------------------------

===== LLM RAW OUTPUT =====
{
  "summary": "Invitation for internship and job assistance program with IIT-Bhubaneswar",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Invitation for internship and job assistance program with IIT-Bhubaneswar', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'High'}

FINAL OUTPUT:
{'summary': 'Invitation for internship and job assistance program with IIT-Bhubaneswar', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'High'}

--------------------------------------------------------------------------------
EMAIL 2
SOURCE: Institutional Sender
SUBJECT: CHARUSAT - FMS - IIIM - Invitation @ Prabandhan 2023 (Exhibition cum Sale) - Inaugural Ceremony
BODY:
charusat - fms - iiim - invitation @ prabandhan 2023 (exhibition cum sale) - inaugural ceremony dear all, greetings! we are thrilled to inform you all that indukaka ipcowala institute of management (iiim) is organizing *prabandhan – 2023 *during november 03-06, 2023 (10:00 am to 09:00 pm). prabandhan is a student-driven event wherein the students collaborate closely with the industries, entrepreneurs, gruh udhyog, and smes to understand the product, devise marketing strategies, learn financial management, negotiation skills, and ultimately sell the product. all students are invited to visit the exhibition and motivate the student participants. *please find the attached invitation and product poster herewith this mail.* *hoping to see you all at prabandhan 2023.* *
--------------------------------------------------------------------------------

===== LLM RAW OUTPUT =====
{
  "summary": "Charusat - FMS - IIM - Invitation @ Prabandhan 2023 (Exhibition cum Sale) - Inaugural Ceremony",
  "label_topic": "Events / Hackathons",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'Charusat - FMS - IIM - Invitation @ Prabandhan 2023 (Exhibition cum Sale) - Inaugural Ceremony', 'label_topic': 'Events / Hackathons', 'label_urgency': 'Low'}

FINAL OUTPUT:
{'summary': 'Charusat - FMS - IIM - Invitation @ Prabandhan 2023 (Exhibition cum Sale) - Inaugural Ceremony', 'label_topic': 'Events / Hackathons', 'label_urgency': 'Low'}

--------------------------------------------------------------------------------
EMAIL 3
SOURCE: External Academic Platform
SUBJECT: Feedback/Queries regarding March 23, 2025 - NPTEL Exams
BODY:
feedback/queries regarding march 23, 2025 - nptel exams nan
--------------------------------------------------------------------------------

===== LLM RAW OUTPUT =====
{
  "summary": "Feedback and queries about NPTEL Exams on March 23, 2025",
  "label_topic": "Exam Notifications",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Feedback and queries about NPTEL Exams on March 23, 2025', 'label_topic': 'Exam Notifications', 'label_urgency': 'High'}

FINAL OUTPUT:
{'summary': 'Feedback and queries about NPTEL Exams on March 23, 2025', 'label_topic': 'Exam Notifications', 'label_urgency': 'High'}

--------------------------------------------------------------------------------
EMAIL 4
SOURCE: Student / Peer
SUBJECT: Gujarat Cultural Elocution Competition – 2025 (University Level) || Registration Deadline: March 6, 2025, 8:00 PM
BODY:
gujarat cultural elocution competition – 2025 (university level) || registration deadline: march 6, 2025, 8:00 pm dear cspit & depstar students, the charusat nss unit is organizing the *university level gujarat cultural elocution competition – 2025* as part of the initiative by the state nss department. we invite interested students to participate and showcase their oratory skills. *date:* march 8, 2025 *time:* 12:15 pm (updated) onwards *venue: *rpcp auditorium *levels:* university → zone → state *topics (choose one):* - character building for nation building - importance of constitution in a citizen’s life - youth: the future of the nation – challenges and responsibilities - values, morality, and ethics: pillars of indian culture - developed india 2047: vision for a better future *eligibility:* participants must be born on or after january 1, 1999. *registration deadline:* march 6, 2025, 8:00 pm *registration link:* <goog_111173522> <url> for further details, please refer to the attached pdfs. for any queries, contact: - *mr. kishan patel* (nss coordinator) – +91 97244 42255 - *mr. dhruv rupapara* (student coordinator) – +91 63539 33976 *we encourage students to participate.* best regards, *nss unit, charusat* ---
--------------------------------------------------------------------------------

===== LLM RAW OUTPUT =====
{
  "summary": "Registration deadline for Gujarat Cultural Elocution Competition - 2025 (University Level) is March 6, 2025, 8:00 PM. Interested students can participate and showcase their oratory skills.",
  "label_topic": "Events / Hackathons",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Registration deadline for Gujarat Cultural Elocution Competition - 2025 (University Level) is March 6, 2025, 8:00 PM. Interested students can participate and showcase their oratory skills.', 'label_topic': 'Events / Hackathons', 'label_urgency': 'Medium'}

FINAL OUTPUT:
{'summary': 'Registration deadline for Gujarat Cultural Elocution Competition - 2025 (University Level) is March 6, 2025, 8:00 PM. Interested students can participate and showcase their oratory skills.', 'label_topic': 'Events / Hackathons', 'label_urgency': 'Medium'}

In [31]:
# ----------------------------------------------------------
# 1. Create balanced subset of 200 emails (UNCHANGED)
# ----------------------------------------------------------

TOTAL_SAMPLES = 200
sources = emails_df["label_source"].unique().tolist()
num_sources = len(sources)
samples_per_source = TOTAL_SAMPLES // num_sources

sampled_parts = []

for source in sources:
    subset = emails_df[emails_df["label_source"] == source]
    
    if len(subset) <= samples_per_source:
        sampled_parts.append(subset)
    else:
        sampled_parts.append(
            subset.sample(n=samples_per_source, random_state=42)
        )

sampled_df = pd.concat(sampled_parts, ignore_index=True)

# Top-up if needed (safe version)
if len(sampled_df) < TOTAL_SAMPLES:
    remaining = emails_df.drop(sampled_df.index, errors="ignore")
    extra_needed = TOTAL_SAMPLES - len(sampled_df)

    if len(remaining) > 0:
        extra_to_take = min(extra_needed, len(remaining))

        sampled_df = pd.concat(
            [
                sampled_df,
                remaining.sample(n=extra_to_take, random_state=42)
            ],
            ignore_index=True
        )


# ----------------------------------------------------------
# 2. Run LLM inference (MODEL → EMAILS)
# ----------------------------------------------------------

for model_name in OLLAMA_MODELS:
    print("\n" + "=" * 100)
    print(f"RUNNING MODEL: {model_name}")
    print("=" * 100 + "\n")

    # Work on a fresh copy per model
    model_df = sampled_df.copy()
    model_df["summary"] = ""
    model_df["label_topic"] = ""
    model_df["label_urgency"] = ""

    for idx, row in model_df.iterrows():
        result = classify_email(
            label_source=row["label_source"],
            subject=row.get("subject", ""),
            clean_text=row.get("clean_text", ""),
            model_name=model_name
        )

        model_df.at[idx, "summary"] = result.get("summary", "")
        model_df.at[idx, "label_topic"] = result.get("label_topic", "")
        model_df.at[idx, "label_urgency"] = result.get("label_urgency", "")

        if idx % 25 == 0:
            print(f"[{model_name}] Processed {idx} / {len(model_df)} emails")

    # ----------------------------------------------------------
    # 3. Save per-model output into EXISTING run directory
    # ----------------------------------------------------------

    safe_model_name = model_name.replace(":", "_").replace("-", "_")
    LLM_OUTPUT_FILE = os.path.join(
        OUTPUT_DIR,
        f"llm_labeled_{safe_model_name}.csv"
    )

    model_df.to_csv(LLM_OUTPUT_FILE, index=False, encoding="utf-8")
    print(f"\nSaved results for model '{model_name}' to:")
    print(LLM_OUTPUT_FILE)

    cont_model = input(
        f"\nFinished model '{model_name}'. Continue to next model? (y/n): "
    ).strip().lower()

    if cont_model != "y":
        break

====================================================================================================
RUNNING MODEL: qwen2.5:7b-instruct-q4_k_m
====================================================================================================


===== LLM RAW OUTPUT =====
{
  "summary": "Access the form design for module 23DCS023 via provided URL.",
  "label_topic": "General Information / Misc",
  "label_urgency": "None"
}
==========================

>>> PARSED RESULT:
{'summary': 'Access the form design for module 23DCS023 via provided URL.', 'label_topic': 'General Information / Misc', 'label_urgency': 'None'}

[qwen2.5:7b-instruct-q4_k_m] Processed 0 / 150 emails

===== LLM RAW OUTPUT =====
{
  "summary": "NetAcad Student Newsletter highlights new platform features and upcoming events.",
  "label_topic": "General Information / Misc",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'NetAcad Student Newsletter highlights new platform features and upcoming events.', 'label_topic': 'General Information / Misc', 'label_urgency': 'Medium'}


===== LLM RAW OUTPUT =====
{
  "summary": "Google alerts you of a recent sign-in on your account.",
  "label_topic": "Administrative / Fees / Counselling",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'Google alerts you of a recent sign-in on your account.', 'label_topic': 'Administrative / Fees / Counselling', 'label_urgency': 'Low'}


===== LLM RAW OUTPUT =====
{
  "summary": "Updates and announcements from Google Developer Program",
  "label_topic": "General Information / Misc",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'Updates and announcements from Google Developer Program', 'label_topic': 'General Information / Misc', 'label_urgency': 'Low'}


===== LLM RAW OUTPUT =====
{
  "summary": "Charusat students invited to apply for IIT Bhubaneswar Wissenaire Internship Program",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Charusat students invited to apply for IIT Bhubaneswar Wissenaire Internship Program', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Congratulations on designing 5 Canva graphics!",
  "label_topic": "General Information / Misc",
  "label_urgency": "None"
}
==========================

>>> PARSED RESULT:
{'summary': 'Congratulations on designing 5 Canva graphics!', 'label_topic': 'General Information / Misc', 'label_urgency': 'None'}


===== LLM RAW OUTPUT =====
{
  "summary": "Meeting report for DS & ML May Internship 2025 on May 12, 2025 at 11:30 AM",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Meeting report for DS & ML May Internship 2025 on May 12, 2025 at 11:30 AM', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'Medium'}


===== LLM RAW OUTPUT =====
{
  "summary": "Apply for AICTE-approved winter internship program with certifications",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Apply for AICTE-approved winter internship program with certifications', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Meeting report for DS & ML May Internship 2025 discussing technical aspects and action items.",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Meeting report for DS & ML May Internship 2025 discussing technical aspects and action items.', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'Medium'}


===== LLM RAW OUTPUT =====
{
  "summary": "Login details for CHARUSAT Sessional January-February-March 2024",
  "label_topic": "Timetable / Schedule Update",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Login details for CHARUSAT Sessional January-February-March 2024', 'label_topic': 'Timetable / Schedule Update', 'label_urgency': 'Medium'}


===== LLM RAW OUTPUT =====
{
  "summary": "Final call for CharUSAT Training Bootcamp enrollment",
  "label_topic": "Certification / Courses",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Final call for CharUSAT Training Bootcamp enrollment', 'label_topic': 'Certification / Courses', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Link to iPhone wallpaper for course 23DCS023",
  "label_topic": "General Information / Misc",
  "label_urgency": "None"
}
==========================

>>> PARSED RESULT:
{'summary': 'Link to iPhone wallpaper for course 23DCS023', 'label_topic': 'General Information / Misc', 'label_urgency': 'None'}


===== LLM RAW OUTPUT =====
{
  "summary": "Free Bolt Pro and Builder Pack for Hackathon Participants",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Free Bolt Pro and Builder Pack for Hackathon Participants', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'Medium'}


===== LLM RAW OUTPUT =====
{
  "summary": "Sync complete with Copilot; explore new features and integrations.",
  "label_topic": "General Information / Misc",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'Sync complete with Copilot; explore new features and integrations.', 'label_topic': 'General Information / Misc', 'label_urgency': 'Low'}


===== LLM RAW OUTPUT =====
{
  "summary": "Signed up for Backtracking and Branch Bound Hackerrank contest",
  "label_topic": "Events / Hackathons",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Signed up for Backtracking and Branch Bound Hackerrank contest', 'label_topic': 'Events / Hackathons', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Invitation to join training and internship program from IBM, Microsoft, and IIT Mandi",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Invitation to join training and internship program from IBM, Microsoft, and IIT Mandi', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Google Cloud Next: AI and Cloud Innovation Updates",
  "label_topic": "Events / Hackathons",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Google Cloud Next: AI and Cloud Innovation Updates', 'label_topic': 'Events / Hackathons', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Recommended: Google Digital Marketing & E-commerce nano",
  "label_topic": "Certification / Courses",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'Recommended: Google Digital Marketing & E-commerce nano', 'label_topic': 'Certification / Courses', 'label_urgency': 'Low'}


===== LLM RAW OUTPUT =====
{
  "summary": "View content by opening the provided URL.",
  "label_topic": "General Information / Misc",
  "label_urgency": "None"
}
==========================

>>> PARSED RESULT:
{'summary': 'View content by opening the provided URL.', 'label_topic': 'General Information / Misc', 'label_urgency': 'None'}


===== LLM RAW OUTPUT =====
{
  "summary": "Invitation for internship and job assistance program with IIT-Bhubaneswar",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Invitation for internship and job assistance program with IIT-Bhubaneswar', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'Medium'}


===== LLM RAW OUTPUT =====
{
  "summary": "Notification about a new login to your X account from a ChromeDesktop on Windows.",
  "label_topic": "Administrative / Fees / Counselling",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Notification about a new login to your X account from a ChromeDesktop on Windows.', 'label_topic': 'Administrative / Fees / Counselling', 'label_urgency': 'Medium'}


===== LLM RAW OUTPUT =====
{
  "summary": "Apply for Microsoft internship program with Teachnook and Wissenaire",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Apply for Microsoft internship program with Teachnook and Wissenaire', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Last chance to save 50% on KodeKloud devops training",
  "label_topic": "Certification / Courses",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'Last chance to save 50% on KodeKloud devops training', 'label_topic': 'Certification / Courses', 'label_urgency': 'Low'}


===== LLM RAW OUTPUT =====
{
  "summary": "Introduction to Jenkins for DevOps: Building Software",
  "label_topic": "Certification / Courses",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'Introduction to Jenkins for DevOps: Building Software', 'label_topic': 'Certification / Courses', 'label_urgency': 'Low'}


===== LLM RAW OUTPUT =====
{
  "summary": "Last chance for Cyber Monday tech training deals from Kodekloud!",
  "label_topic": "Certification / Courses",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'Last chance for Cyber Monday tech training deals from Kodekloud!', 'label_topic': 'Certification / Courses', 'label_urgency': 'Low'}


===== LLM RAW OUTPUT =====
{
  "summary": "Recommended reading: 'AI for Everyone'",
  "label_topic": "General Information / Misc",
  "label_urgency": "None"
}
==========================

>>> PARSED RESULT:
{'summary': "Recommended reading: 'AI for Everyone'", 'label_topic': 'General Information / Misc', 'label_urgency': 'None'}

[qwen2.5:7b-instruct-q4_k_m] Processed 25 / 150 emails

===== LLM RAW OUTPUT =====
{
  "summary": "Register for Bolt's $1M Hackathon starting May 30",
  "label_topic": "Hackathons",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': "Register for Bolt's $1M Hackathon starting May 30", 'label_topic': 'Hackathons', 'label_urgency': 'Low'}


===== LLM RAW OUTPUT =====
{
  "summary": "Signed up for String Matching contest on Hackerrank",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Signed up for String Matching contest on Hackerrank', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'Medium'}


===== LLM RAW OUTPUT =====
{
  "summary": "Opportunity for free DevOps training sponsored by your company.",
  "label_topic": "Certification / Courses",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'Opportunity for free DevOps training sponsored by your company.', 'label_topic': 'Certification / Courses', 'label_urgency': 'Low'}


===== LLM RAW OUTPUT =====
{
  "summary": "Canva offers festive templates for Diwali celebrations.",
  "label_topic": "General Information / Misc",
  "label_urgency": "None"
}
==========================

>>> PARSED RESULT:
{'summary': 'Canva offers festive templates for Diwali celebrations.', 'label_topic': 'General Information / Misc', 'label_urgency': 'None'}


===== LLM RAW OUTPUT =====
{
  "summary": "DevOps career opportunity with up to 50% off until June 30",
  "label_topic": "Certification / Courses",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'DevOps career opportunity with up to 50% off until June 30', 'label_topic': 'Certification / Courses', 'label_urgency': 'Low'}


===== LLM RAW OUTPUT =====
{
  "summary": "Mandatory Wipro Dice ID Certification Internship Program for CharUSAT Students",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Mandatory Wipro Dice ID Certification Internship Program for CharUSAT Students', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Shortlisted for Accenture Summer Internship; Apply by Today's Deadline",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': "Shortlisted for Accenture Summer Internship; Apply by Today's Deadline", 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Explore resources and learn new skills to boost your career.",
  "label_topic": "General Information / Misc",
  "label_urgency": "None"
}
==========================

>>> PARSED RESULT:
{'summary': 'Explore resources and learn new skills to boost your career.', 'label_topic': 'General Information / Misc', 'label_urgency': 'None'}


===== LLM RAW OUTPUT =====
{
  "summary": "Last chance to save up to 50% on DevOps training before the sale ends.",
  "label_topic": "Certification / Courses",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Last chance to save up to 50% on DevOps training before the sale ends.', 'label_topic': 'Certification / Courses', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Invitation for Summer Placement Training and Internship Program",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Invitation for Summer Placement Training and Internship Program', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Link to content related to course 23DCS023",
  "label_topic": "General Information / Misc",
  "label_urgency": "None"
}
==========================

>>> PARSED RESULT:
{'summary': 'Link to content related to course 23DCS023', 'label_topic': 'General Information / Misc', 'label_urgency': 'None'}


===== LLM RAW OUTPUT =====
{
  "summary": "Join a webinar to assess and close DevOps skill gaps on March 12, 2025.",
  "label_topic": "Events / Hackathons",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Join a webinar to assess and close DevOps skill gaps on March 12, 2025.', 'label_topic': 'Events / Hackathons', 'label_urgency': 'Medium'}


===== LLM RAW OUTPUT =====
{
  "summary": "Opportunity for discounted internship and training program at CHARUSAT University",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Opportunity for discounted internship and training program at CHARUSAT University', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "LeetCode Weekly Challenge Update",
  "label_topic": "General Information / Misc",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'LeetCode Weekly Challenge Update', 'label_topic': 'General Information / Misc', 'label_urgency': 'Low'}


===== LLM RAW OUTPUT =====
{
  "summary": "Invitation to attend Prabandhan 2023 Inaugural Ceremony",
  "label_topic": "Events / Hackathons",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'Invitation to attend Prabandhan 2023 Inaugural Ceremony', 'label_topic': 'Events / Hackathons', 'label_urgency': 'Low'}


===== LLM RAW OUTPUT =====
{
  "summary": "Upcoming Start Up Conclave and Accelerator Program Information",
  "label_topic": "Internship / Placement Opportunities",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Upcoming Start Up Conclave and Accelerator Program Information', 'label_topic': 'Internship / Placement Opportunities', 'label_urgency': 'Medium'}


===== LLM RAW OUTPUT =====
{
  "summary": "Attend Live Webinar on SWAYAM Plus on May 13, 2024",
  "label_topic": "Events / Hackathons",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Attend Live Webinar on SWAYAM Plus on May 13, 2024', 'label_topic': 'Events / Hackathons', 'label_urgency': 'Medium'}


===== LLM RAW OUTPUT =====
{
  "summary": "Upload practical file and HackerRank PDF by 03-12-2023",
  "label_topic": "Assignment or Submission",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Upload practical file and HackerRank PDF by 03-12-2023', 'label_topic': 'Assignment or Submission', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Register for StackHack 2.0 for prizes and mentorship",
  "label_topic": "Events / Hackathons",
  "label_urgency": "Low"
}
==========================

>>> PARSED RESULT:
{'summary': 'Register for StackHack 2.0 for prizes and mentorship', 'label_topic': 'Events / Hackathons', 'label_urgency': 'Low'}


===== LLM RAW OUTPUT =====
{
  "summary": "Lab manual and journal due date, Quiz 2 for Engineering Physics - 2 (PY143)",
  "label_topic": "Assignment or Submission",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Lab manual and journal due date, Quiz 2 for Engineering Physics - 2 (PY143)', 'label_topic': 'Assignment or Submission', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Reminder and instructions for MA144 Engineering Mathematics-II quiz today.",
  "label_topic": "Exam Notifications",
  "label_urgency": "Critical"
}
==========================

>>> PARSED RESULT:
{'summary': 'Reminder and instructions for MA144 Engineering Mathematics-II quiz today.', 'label_topic': 'Exam Notifications', 'label_urgency': 'Critical'}


===== LLM RAW OUTPUT =====
{
  "summary": "Second internal examination schedule for Semester 2 has been released.",
  "label_topic": "Exam Notifications",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Second internal examination schedule for Semester 2 has been released.', 'label_topic': 'Exam Notifications', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Video recordings for Sheet-2 preparation in ME145 EOE-EG are available.",
  "label_topic": "Assignment or Submission",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Video recordings for Sheet-2 preparation in ME145 EOE-EG are available.', 'label_topic': 'Assignment or Submission', 'label_urgency': 'High'}


===== LLM RAW OUTPUT =====
{
  "summary": "Registration open for certification course on Internet of Vehicles (IoV): 5G and Beyond Autonomous and Connected Cars",
  "label_topic": "Certification / Courses",
  "label_urgency": "Medium"
}
==========================

>>> PARSED RESULT:
{'summary': 'Registration open for certification course on Internet of Vehicles (IoV): 5G and Beyond Autonomous and Connected Cars', 'label_topic': 'Certification / Courses', 'label_urgency': 'Medium'}


===== LLM RAW OUTPUT =====
{
  "summary": "Last day for enrollment and exam registration for Jan-Apr 2024 semester",
  "label_topic": "Timetable / Schedule Update",
  "label_urgency": "High"
}
==========================

>>> PARSED RESULT:
{'summary': 'Last day for enrollment and exam registration for Jan-Apr 2024 semester', 'label_topic': 'Timetable / Schedule Update', 'label_urgency': 'High'}


NameError: name 'emails_df' is not defined

In [ ]:
# ----------------------------------------------------------

# Model Evaluation Metrics

# ----------------------------------------------------------

import pandas as pd

from sklearn.metrics import classification_report, accuracy_score, confusion_matrix


# Load ground truth and model predictions

ground_truth = pd.read_csv("evaluation_dataset_ground_truth.csv", dtype=str, keep_default_na=False)

# Replace with the actual model output file you want to evaluate

model_output = pd.read_csv(OUTPUT_FILE, dtype=str, keep_default_na=False)


# Ensure columns match for comparison

# For example, compare 'label_topic' and 'label_urgency'

for label in ["label_topic", "label_urgency"]:
    print(f"\n=== Evaluation for {label} ===")
    y_true = ground_truth[label]
    y_pred = model_output[label]
    print(classification_report(y_true, y_pred))
    print("Confusion Matrix:")
    print(confusion_matrix(y_true, y_pred))
    print(f"Accuracy: {accuracy_score(y_true, y_pred):.4f}")